Repository Qiskit/qiskit-metal, pull requests merged in 2021-07, with the labels that each got.

#628 Install details, broken links and images
  README.md
  docs/faq.rst
  docs/installation.rst
Labels: documentation & tutorials

#626 551 nick new
  docs/apidocs/qiskit_metal.qlibrary.jj_dolan.rst
  docs/apidocs/qiskit_metal.qlibrary.jj_manhattan.rst
  qiskit_metal/qlibrary/__init__.py
  qiskit_metal/qlibrary/qubits/JJ_Dolan.py
  qiskit_metal/qlibrary/qubits/JJ_Manhattan.py
  qiskit_metal/tests/test_qlibrary_1_instantiate.py
  qiskit_metal/tests/test_qlibrary_2_options.py
  qiskit_metal/tests/test_qlibrary_3_functionality.py
  tutorials/Appendix B Quick topics/JJ Demo Notebook.ipynb
Labels: documentation & tutorials, enhancement

#640 Updates to interdigitated and concentric transmon qcomponents
  qiskit_metal/qlibrary/qubits/Transmon_Interdigitated.py
  qiskit_metal/qlibrary/qubits/transmon_concentric.py
  qiskit_metal/tests/test_qlibrary_2_options.py
Labels: bug, general, renderers: other

#650 CPW kappa fix nick
  qiskit_metal/analyses/em/cpw_calculations.py
  qiskit_metal/analyses/em/kappa_calculation.py
  qiskit_metal/tests/test_analyses_2_functionality.py
Labels: analysis: others, bug
